name: lista_afazeres
description: Um aplicativo simples para gerenciamento de tarefas.

# Versão do seu aplicativo
version: 1.0.0+1

# Defina os caminhos das dependências
dependencies:
  flutter:
    sdk: flutter
  # Outras dependências podem ser listadas aqui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Definição do SDK do Dart
environment:
  sdk: ">=3.6.0 <4.0.0"

# Configurações adicionais do Flutter
flutter:
  uses-material-design: true
  assets:
    # Caso você tenha assets como imagens ou fontes
    # - assets/images/
