// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTixEp8GeEJyGblaii_KXRG1Hbdk3fKE',
    appId: '1:145856781276:web:986a57549f25b222a60d19',
    messagingSenderId: '145856781276',
    projectId: 'appsh-44b4a',
    authDomain: 'appsh-44b4a.firebaseapp.com',
    storageBucket: 'appsh-44b4a.firebasestorage.app',
    measurementId: 'G-4YKZK0WTGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqlMKqqMq5hamZWLrV3WaMrjxlZHOMGOk',
    appId: '1:145856781276:android:38d10f4de5a0580fa60d19',
    messagingSenderId: '145856781276',
    projectId: 'appsh-44b4a',
    storageBucket: 'appsh-44b4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwNas6J5Hd1qcG1gw8iJHz_-2IbPUtltk',
    appId: '1:145856781276:ios:edfcc64f08387845a60d19',
    messagingSenderId: '145856781276',
    projectId: 'appsh-44b4a',
    storageBucket: 'appsh-44b4a.firebasestorage.app',
    iosBundleId: 'com.example.appsh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwNas6J5Hd1qcG1gw8iJHz_-2IbPUtltk',
    appId: '1:145856781276:ios:edfcc64f08387845a60d19',
    messagingSenderId: '145856781276',
    projectId: 'appsh-44b4a',
    storageBucket: 'appsh-44b4a.firebasestorage.app',
    iosBundleId: 'com.example.appsh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjTixEp8GeEJyGblaii_KXRG1Hbdk3fKE',
    appId: '1:145856781276:web:91f2d84aed4ea104a60d19',
    messagingSenderId: '145856781276',
    projectId: 'appsh-44b4a',
    authDomain: 'appsh-44b4a.firebaseapp.com',
    storageBucket: 'appsh-44b4a.firebasestorage.app',
    measurementId: 'G-F83D9XQPH4',
  );

}